force-app/main/default/objects/Asset/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <description>Type of device for the subscriber. Values can be Mobile, Tablet or Phone</description>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Wearable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Make_and_Model__c.field-meta.xml
<CustomField>
    <fullName>Make_and_Model__c</fullName>
    <description>Device name and version.</description>
    <label>Make and Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Phone_Number_Display__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Display__c</fullName>
    <description>Subscriber&apos;s phone number in a readable format.</description>
    <label>Phone Number Display</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to the plan this asset is related to.</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlimited_Data__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to track if Data is unlimited for this subscriber</description>
    <label>Unlimited Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlimited_Talk__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Talk__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to track if Talk is unlimited for this subscriber</description>
    <label>Unlimited Talk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlimited_Text__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to track if Text is unlimited for this subscriber</description>
    <label>Unlimited Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>Name of the person the device is related to.</description>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <description>Account that represents the service provided to a customer.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Account__c/fields/Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Number__c</fullName>
    <description>Account number that serves as external identifier for billing accounts.</description>
    <externalId>true</externalId>
    <label>Billing Account Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to the billing account this plan is related to.</description>
    <label>Billing Account Number</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usage__c/Usage__c.object-meta.xml
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Usage__c/fields/Allotted_Usage__c.field-meta.xml
<CustomField>
    <fullName>Allotted_Usage__c</fullName>
    <description>Field used to store the total usage assigned for that subscriber in the plan.</description>
    <label>Allotted Usage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Usage__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Lookup relationship to the asset this usage record is related to.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Usage</relationshipLabel>
    <relationshipName>Usage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Usage__c/fields/Current_Usage__c.field-meta.xml
<CustomField>
    <fullName>Current_Usage__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Field to store the amount of usage for data, text, or talk. The Usage Type field will determine the type of usage this is.</description>
    <label>Current Usage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Usage__c/fields/Usage_Type__c.field-meta.xml
<CustomField>
    <fullName>Usage_Type__c</fullName>
    <description>Type of usage for this record. Values can be Data, Text, Talk</description>
    <label>Usage Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Talk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeviceUsageControllerTest.cls
@isTest
public with sharing class DeviceUsageControllerTest {
  @TestSetup
  static void makeData() {
    Account account = new Account();
    account.Name = 'Test Account';
    insert account;

    Billing_Account__c billingAccount = new Billing_Account__c();
    billingAccount.Name = 'Test Account';
    billingAccount.Billing_Account_Number__c = '1';
    insert billingAccount;

    Plan__c plan = new Plan__c();
    plan.Name = 'Test Plan';
    plan.Billing_Account_Number__c = billingAccount.Id;
    insert plan;

    Asset asset = new Asset();
    asset.Name = 'Test Asset';
    asset.AccountId = account.Id;
    asset.Make_and_Model__c = 'iPhone X';
    asset.User__c = 'Test User';
    asset.Phone_Number_Display__c = '(123) 456-7890';
    asset.Device_Type__c = 'Phone';
    asset.Unlimited_Data__c = false;
    asset.Unlimited_Talk__c = false;
    asset.Unlimited_Text__c = false;
    asset.Plan__c = plan.Id;
    insert asset;

    Set<String> types = new Set<String>{ 'Data', 'Text', 'Talk' };
    List<Usage__c> usages = new List<Usage__c>();
    for (String type : types) {
      Usage__c usage = new Usage__c();
      usage.Allotted_Usage__c = 100;
      usage.Current_Usage__c = 50;
      usage.Asset__c = asset.Id;
      usage.Usage_Type__c = type;
      usages.add(usage);
    }
    insert usages;
  }

  @isTest
  static void getPlans_givenBillingAccountId_shouldReturnAllPlans() {
    Billing_Account__c billingAccount = [
      SELECT Id
      FROM Billing_Account__c
      LIMIT 1
    ];
    Test.startTest();
    DeviceUsageController.PlanWrapper wrapper = DeviceUsageController.getPlans(
      billingAccount.Id,
      'Data'
    );
    Test.stopTest();
    System.assertEquals(1, wrapper.plans.size(), 'Should only be one plan');
    System.assertEquals(
      1,
      wrapper.plans[0].Assets__r.size(),
      'Should only be one asset'
    );
    System.assertEquals(
      1,
      wrapper.usageMap.keySet().size(),
      'Should only be one usage'
    );
    System.assertEquals(
      'Data',
      wrapper.usageMap.get(wrapper.plans[0].Assets__r[0].Id).Usage_Type__c,
      'Should have gotten only usages with type of data'
    );
  }

  @isTest
  static void getPlans_givenPlanId_shouldReturnUsageOfSpecifiedType() {
    Plan__c plan = [SELECT Id FROM Plan__c LIMIT 1];
    Test.startTest();
    DeviceUsageController.PlanWrapper wrapper = DeviceUsageController.getPlans(
      plan.Id,
      'Text'
    );
    Test.stopTest();
    System.assertEquals(1, wrapper.plans.size(), 'Should only be one plan');
    System.assertEquals(
      1,
      wrapper.plans[0].Assets__r.size(),
      'Should only be one asset'
    );
    System.assertEquals(
      1,
      wrapper.usageMap.keySet().size(),
      'Should only be one usage'
    );
    System.assertEquals(
      'Text',
      wrapper.usageMap.get(wrapper.plans[0].Assets__r[0].Id).Usage_Type__c,
      'Should have gotten only usages with type of data'
    );
  }
}