force-app/main/default/objects/Asset/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <description>Type of device for the subscriber. Values can be Mobile, Tablet or Phone</description>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Wearable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Make_and_Model__c.field-meta.xml
<CustomField>
    <fullName>Make_and_Model__c</fullName>
    <description>Device name and version.</description>
    <label>Make and Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Phone_Number_Display__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_Display__c</fullName>
    <description>Subscriber&apos;s phone number in a readable format.</description>
    <label>Phone Number Display</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to the plan this asset is related to.</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlimited_Data__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to track if Data is unlimited for this subscriber</description>
    <label>Unlimited Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlimited_Talk__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Talk__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to track if Talk is unlimited for this subscriber</description>
    <label>Unlimited Talk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Unlimited_Text__c.field-meta.xml
<CustomField>
    <fullName>Unlimited_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to track if Text is unlimited for this subscriber</description>
    <label>Unlimited Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>Name of the person the device is related to.</description>
    <label>User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to the billing account this plan is related to.</description>
    <label>Billing Account Number</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Full description of the product for this plan.</description>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usage__c/Usage__c.object-meta.xml
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Usage__c/fields/Allotted_Usage__c.field-meta.xml
<CustomField>
    <fullName>Allotted_Usage__c</fullName>
    <description>Field used to store the total usage assigned for that subscriber in the plan.</description>
    <label>Allotted Usage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Usage__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Lookup relationship to the asset this usage record is related to.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Usage</relationshipLabel>
    <relationshipName>Usage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Usage__c/fields/Current_Usage__c.field-meta.xml
<CustomField>
    <fullName>Current_Usage__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Field to store the amount of usage for data, text, or talk. The Usage Type field will determine the type of usage this is.</description>
    <label>Current Usage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Usage__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <description>Formula field to identify the unit of measure for this usage record depending on the usage type.</description>
    <formula>CASE(TEXT(Usage_Type__c),
&quot;Data&quot;, &quot;GB&quot;,
&quot;Text&quot;, &quot;SMS&quot;,
&quot;Talk&quot;, &quot;Minutes&quot;, 
&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Usage__c/fields/Usage_Type__c.field-meta.xml
<CustomField>
    <fullName>Usage_Type__c</fullName>
    <description>Type of usage for this record. Values can be Data, Text, Talk</description>
    <label>Usage Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Talk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/deviceUsageController.cls
public with sharing class deviceUsageController {

    class PlanWrapper {
        @AuraEnabled public List<Plan__c> plans {get;set;}
        @AuraEnabled public Map<Id,List<Usage__c>> usageMap {get;set;}

        public PlanWrapper(List<Plan__c> plans, Map<Id,List<Usage__c>> usageMap) {
            this.plans = plans;
            this.usageMap = usageMap;
        }
    }

    @AuraEnabled
    public static PlanWrapper getPlans(Id billingAccountId) {
        try {
            List<Plan__c> plans =  [SELECT Id, Product__c, 
                                        (SELECT Id, Make_And_Model__c, User__c, Phone_Number_Display__c, Device_Type__c, Unlimited_Data__c, Unlimited_Talk__c, Unlimited_Text__c
                                        FROM Assets__r)
                                    FROM Plan__c
                                    WHERE Billing_Account_Number__c = :billingAccountId];

            Set<Id> assetIds = new Set<Id>();
            for (Plan__c plan : plans) {
                for (Asset asset : plan.Assets__r) {
                    assetIds.add(asset.Id);
                }
            }

            List<Usage__c> usageInfo = [SELECT Id, Allotted_Usage__c, Current_Usage__c, Asset__c, Unit_of_Measure__c, Usage_Type__c
                                        FROM Usage__c
                                        WHERE Asset__c IN :assetIds];

            Map<Id,List<Usage__c>> usageMap = new Map<Id,List<Usage__c>>();
            for (Usage__c usage : usageInfo) {
                if (!usageMap.containsKey(usage.Asset__c)) {
                    usageMap.put(usage.Asset__c, new List<Usage__c>());  
                }
                usageMap.get(usage.Asset__c).add(usage);
            }

            PlanWrapper wrapper = new PlanWrapper(plans, usageMap);
            return wrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}